### ISSUE TITLE
AWT does not work with glfw on Mac OS. Image loading freezes the program

### ISSUE THREAD

**Issue by Wasabi375** [kotlin-graphics/gli#2]
Using AWT and glfw together on a mac leads to a deadlock. The reason for that is that both programs try to run an event loop on the main thread AFAIK (https://github.com/LWJGL/lwjgl3/issues/68). We use awt to load images.

The proposed solution for this (from lwjgl) is to use stb instead. The C bindings for this are part of lwjgl.

**Comment by elect86** [comment]
It looks like we don't have so much choice then..

So stb be

I'm quite absorbed by gln atm, if you have time and will, go for it :), otherwise I'll do it as soon as I have some free time again (MacOS is a very low priority for me)

**Comment by Wasabi375** [comment]
I mostly develop on a mac so it's a bit of a priority for me. Also since I ran into this problem I guess I will have to do this anyway 😉

**Comment by Wasabi375** [comment]
So I started looking into this. We already import 3 formats without any 3rd party libs (dds, kmg and ktx), so they should work the same. All other formats are supported by stb and stb even supports a few additional formats(psd, hdr, pic, and pnm), which I will add to gli if I find a test image I can use.

The only problem I have is that we currently support wbmp files. I don't think there is anyone out there still using them as they only support monochrome colors(black, white without grays). So I think it's fine dropping that. Worst case we have to write an import for that, but as far as I can tell the format is really simple so that wouldn't be too bad.

**Comment by elect86** [comment]
> I mostly develop on a mac so it's a bit of a priority for me. Also since I ran into this problem I guess I will have to do this anyway 😉


Ok 👍 


> So I started looking into this. We already import 3 formats without any 3rd party libs (dds, kmg and ktx), so they should work the same. All other formats are supported by stb and stb even supports a few additional formats(psd, hdr, pic, and pnm), which I will add to gli if I find a test image I can use.

The fact we can easily support more formats with a dependency we already use (and even eliminate another one, tga importer) is very nice.

For the tests, I may suggest that the [stb tests](https://github.com/nothings/stb/tree/master/tests) could be an interesting place to start from.
 
> The only problem I have is that we currently support wbmp files. I don't think there is anyone out there still using them as they only support monochrome colors(black, white without grays). So I think it's fine dropping that. Worst case we have to write an import for that, but as far as I can tell the format is really simple so that wouldn't be too bad.

Never heard of it before, but it looks indeed [quite simple](https://en.wikipedia.org/wiki/Wireless_Application_Protocol_Bitmap_Format)


Type | uintvar | variable | Type of the image, and is 0 for monochrome bitmaps.
-- | -- | -- | --
Fixed header | byte | 1 | Reserved. Always 0.
Width | uintvar | variable | Width of the image in pixels.
Height | uintvar | variable | Height of the image in pixels.
Data | byte array | variable | Data bytes arranged in rows – one bit per pixel. A black pixel is  denoted by 0 and a white pixel is denoted by 1. Where the row length is  not divisible by 8, the row is 0-padded to the byte boundary.

It shouldnt be hard to implement it if really needed
